<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before'); ?>

<form action="<?php echo $block->getUrl('checkout/cart/updatePost') ?>" method="post">
  <?php echo $block->getBlockHtml('formkey'); ?>
  <div class="heading">
    <div>ARTIKEL</div>
    <div>MENGE</div>
    <div>PREIS</div>
    <div>GESAMT</div>
  </div>
  <?php foreach ($block->getItems() as $_item): ?>
  <div class="product clear">
    <div class="preview clear">
      <div class="picture left">
        <a href="<?php echo $_item->getProduct()->getProductUrl(); ?>">
          <img src="/pub/media/catalog/product<?php echo $_item->getProduct()->getImage(); ?>" alt="<?php echo $_item->getName(); ?>" />
        </a>
      </div>
      <div class="description left">
        <h2><?php echo $_item->getName(); ?></h2>
        <span>Schwarztee -entkoffeiniert-</span>
      </div>
    </div>
    <div class="count fw-500">
      <input type="number" name="cart[<?php echo $_item->getId(); ?>][qty]" class="input-number" value="<?php echo $_item->getQty(); ?>" min="0" max="99" />
    </div>
    <div class="price">
      <?php printf('%.2f', $_item->getPrice()); ?>€
    </div>
    <div class="total">
      <?php printf('%.2f', $_item->getPrice() * $_item->getQty()); ?>€*
    </div>
    <div class="right fa fa-close">
    </div>
  </div>
  <?php endforeach; ?>
</form>
