<header class="w100p">
  <div class="wrapper h100p clear">
    <div class="logo-wrapper left">
      <a class="logo" href="/">
        <img src="<?php echo $this->getViewFileUrl('img/header/logo.png'); ?>" alt="Logo">
      </a>
    </div>
    <div class="content-wrapper left">
      <div class="general clear">
        <div class="list left">
          <div class="list-item gift">
            <a href="">Gutscheine</a>
          </div>
          <div class="list-item ring">
            <a href="">Hilfe &amp; Kontakt</a>
          </div>
          <div class="list-item phone">
            <a href="tel:05012341356468">(050) - 1234 1356468</a>
          </div>
        </div>
        <div class="left ico-facebook">
          <a href="#">
            <i class="fa fa-facebook-official"></i>
          </a>
        </div>
        <div class="list right">
          <div class="list-item language">Deutsch</div>
          <div class="list-item user">
            <a href="">Mein Konto</a>
          </div>
          <div class="list-item lock">
            <a href="/customer/account/login/">abmelden</a>
          </div>
        </div>
      </div>
      <div class="social-login">
        Besuche tealiko auch auf: <i class="fa fa-facebook-official"></i>
      </div>
      <div class="clear search-cart">
        <div class="search left clear">
          <form class="form minisearch" id="search_mini_form" action="/catalogsearch/result/" method="get">
            <input type="text" name="q" class="input left" placeholder="Durchsuche den tealiko Online-Shop...">
            <button class="btn fa fa-search left" type="submit"></button>
          </form>
        </div>
        <div id="cart-widget" class="cart right clear">
          <a href="/checkout/cart" class="fa fa-shopping-cart left"></a>
          <div class="products left">0</div>
          <div class="price left">€0.00</div>
        </div>
      </div>
    </div>
  </div>
</header>
