<div class="holder">
  <div class="notification">
    <div class="text"><i>JETZT NEU:</i>   KosTenlose lieferung ab 20€ Bestellwert innerhalb von Deutschland.</div>
    <div class="close"><span>schließen</span> <i class="fa fa-close"></i></div>
  </div>
  <header class="w100p">
    <div class="wrapper h100p clear">
      <div class="logo-wrapper left">
        <a class="logo" href="">
          <img src="img/header/logo.png" alt="Logo" />
        </a>
      </div>
      <div class="content-wrapper left">
        <div class="general clear">
          <div class="list left">
            <div class="list-item gift">
              <a href="">Gutscheine</a>
            </div>
            <div class="list-item ring">
              <a href="">Hilfe & Kontakt</a>
            </div>
            <div class="list-item phone">
              <a href="">(050) - 1234 1356468</a>
            </div>
          </div>
          <div class="left ico-facebook">
            <a href="#">
              <i class="fa fa-facebook-official"></i>
            </a>
          </div>
          <div class="list right">
            <div class="list-item language">Deutsch</div>
            <div class="list-item user">
              <a href="">Mein Konto</a>
            </div>
            <div class="list-item lock">
              <a href="">abmelden</a>
            </div>
          </div>
        </div>
        <div class="social-login">
          Besuche tealiko auch auf: <i class="fa fa-facebook-official"></i>
        </div>
        <div class="clear search-cart">
          <div class="search left clear">
            <input type="text" class="input left" placeholder="Durchsuche den tealiko Online-Shop..." />
            <button class="btn fa fa-search left"></button>
          </div>
          <div class="cart right clear">
            <div class="products left">0</div>
            <div class="price left">0.00 <i class="fa fa-euro"></i></div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <nav class="menu-wrapper">
    <div class="wrapper main-menu">
      <ul class="menu homepage">

        <li class="menu-item">
          <a href="#">Home</a>
        </li>
        <li class="menu-item with-arrow">
          <a href="#">Tee</a>
          <ul class="submenu">
            <li class="menu-subitem">
              <span>Schwarztee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -entkoffeiniert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Assam</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ceylon</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ostfriesen & Blatt-Mischung</a>
            </li>
            <li class="menu-subitem">
              <span>Grüner Tee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Grün -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Weißer Tee -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Japan</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <span>Oolong</span>
            </li>
            <li class="menu-subitem">
              <span>Früchtetee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte Sortiment</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <span>Kräutertee & Gewürze</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter & Gewürze - pur -</a>
            </li>
            <li class="menu-subitem">
              <span>Rooibostee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos grün</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Honeybush</a>
            </li>
            <li class="menu-subitem">
              <span>Bio & Natürliches Aroma</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Bio Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ayurveda Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Natürlich aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Nicht aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <span>Ostertee</span>
            </li>
          </ul>
        </li>

        <li class="menu-item with-arrow">
          <a href="#">Kaffee</a>
          <ul class="submenu">
            <li class="menu-subitem">
              <span>Schwarztee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -entkoffeiniert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Assam</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ceylon</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ostfriesen & Blatt-Mischung</a>
            </li>
            <li class="menu-subitem">
              <span>Grüner Tee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Grün -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Weißer Tee -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Japan</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <span>Oolong</span>
            </li>
            <li class="menu-subitem">
              <span>Früchtetee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte Sortiment</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <span>Kräutertee & Gewürze</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter & Gewürze - pur -</a>
            </li>
            <li class="menu-subitem">
              <span>Rooibostee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos grün</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Honeybush</a>
            </li>
            <li class="menu-subitem">
              <span>Bio & Natürliches Aroma</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Bio Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ayurveda Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Natürlich aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Nicht aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <span>Ostertee</span>
            </li>
          </ul>
        </li>

        <li class="menu-item with-arrow">
          <a href="#">Geschenke</a>
          <ul class="submenu">
            <li class="menu-subitem">
              <span>Schwarztee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -entkoffeiniert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Assam</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ceylon</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ostfriesen & Blatt-Mischung</a>
            </li>
            <li class="menu-subitem">
              <span>Grüner Tee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Grün -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Weißer Tee -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Japan</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <span>Oolong</span>
            </li>
            <li class="menu-subitem">
              <span>Früchtetee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte Sortiment</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <span>Kräutertee & Gewürze</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter & Gewürze - pur -</a>
            </li>
            <li class="menu-subitem">
              <span>Rooibostee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos grün</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Honeybush</a>
            </li>
            <li class="menu-subitem">
              <span>Bio & Natürliches Aroma</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Bio Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ayurveda Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Natürlich aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Nicht aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <span>Ostertee</span>
            </li>
          </ul>
        </li>

        <li class="menu-item with-arrow">
          <a href="#">Raritäten</a>
          <ul class="submenu">
            <li class="menu-subitem">
              <span>Schwarztee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -entkoffeiniert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Assam</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ceylon</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ostfriesen & Blatt-Mischung</a>
            </li>
            <li class="menu-subitem">
              <span>Grüner Tee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Grün -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Weißer Tee -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Japan</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <span>Oolong</span>
            </li>
            <li class="menu-subitem">
              <span>Früchtetee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte Sortiment</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <span>Kräutertee & Gewürze</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter & Gewürze - pur -</a>
            </li>
            <li class="menu-subitem">
              <span>Rooibostee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos grün</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Honeybush</a>
            </li>
            <li class="menu-subitem">
              <span>Bio & Natürliches Aroma</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Bio Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ayurveda Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Natürlich aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Nicht aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <span>Ostertee</span>
            </li>
          </ul>
        </li>

        <li class="menu-item with-arrow">
          <a href="#">Wellness</a>
          <ul class="submenu">
            <li class="menu-subitem">
              <span>Schwarztee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -entkoffeiniert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Assam</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ceylon</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ostfriesen & Blatt-Mischung</a>
            </li>
            <li class="menu-subitem">
              <span>Grüner Tee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Grün -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Weißer Tee -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Japan</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <span>Oolong</span>
            </li>
            <li class="menu-subitem">
              <span>Früchtetee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte Sortiment</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <span>Kräutertee & Gewürze</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter & Gewürze - pur -</a>
            </li>
            <li class="menu-subitem">
              <span>Rooibostee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos grün</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Honeybush</a>
            </li>
            <li class="menu-subitem">
              <span>Bio & Natürliches Aroma</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Bio Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ayurveda Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Natürlich aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Nicht aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <span>Ostertee</span>
            </li>
          </ul>
        </li>

        <li class="menu-item with-arrow">
          <a href="#">Aktuell</a>
          <ul class="submenu">
            <li class="menu-subitem">
              <span>Schwarztee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -entkoffeiniert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Assam</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ceylon</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ostfriesen & Blatt-Mischung</a>
            </li>
            <li class="menu-subitem">
              <span>Grüner Tee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Grün -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Weißer Tee -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Japan</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <span>Oolong</span>
            </li>
            <li class="menu-subitem">
              <span>Früchtetee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte Sortiment</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <span>Kräutertee & Gewürze</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter & Gewürze - pur -</a>
            </li>
            <li class="menu-subitem">
              <span>Rooibostee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos grün</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Honeybush</a>
            </li>
            <li class="menu-subitem">
              <span>Bio & Natürliches Aroma</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Bio Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ayurveda Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Natürlich aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Nicht aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <span>Ostertee</span>
            </li>
          </ul>
        </li>

        <li class="menu-item with-arrow">
          <a href="#">Zubehör</a>
          <ul class="submenu">
            <li class="menu-subitem">
              <span>Schwarztee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Schwarz -entkoffeiniert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Assam</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ceylon</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ostfriesen & Blatt-Mischung</a>
            </li>
            <li class="menu-subitem">
              <span>Grüner Tee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Grün -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Weißer Tee -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Darjeeling</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Japan</a>
            </li>
            <li class="menu-subitem">
              <a href="#">China</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Andere Länder & Gebiete</a>
            </li>
            <li class="menu-subitem">
              <span>Oolong</span>
            </li>
            <li class="menu-subitem">
              <span>Früchtetee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte Sortiment</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Früchte -magenschonend-</a>
            </li>
            <li class="menu-subitem">
              <span>Kräutertee & Gewürze</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Kräuter & Gewürze - pur -</a>
            </li>
            <li class="menu-subitem">
              <span>Rooibostee</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos -aromatisiert-</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Rooibos grün</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Honeybush</a>
            </li>
            <li class="menu-subitem">
              <span>Bio & Natürliches Aroma</span>
            </li>
            <li class="menu-subitem">
              <a href="#">Bio Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Ayurveda Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Natürlich aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <a href="#">Nicht aromatisierter Tee</a>
            </li>
            <li class="menu-subitem">
              <span>Ostertee</span>
            </li>
          </ul>
        </li>

      </ul>
    </div>
  </nav>
</div>
