<?php
  $_product = $block->getProduct();
  $_images = $_product->getMediaGalleryImages();

  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
  $rating = $objectManager->create('Magento\Review\Model\Rating');

  // Get product options (like color/weight/size)
  $productOptions = $objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable')->getConfigurableAttributesAsArray($product);
?>

<div class="clear product-info">
  <div class="left slider-container">
    <div class="heading-1"><?php echo $_product->getName() ?></div>
    <div class="clear">
      <?php $ratingData = $rating->getEntitySummary($_product->getId())->getData(); ?>
      <?php if (!empty($ratingData['sum']) && !empty($ratingData['count'])) : ?>
        <div class="text left fw-600">Kunden-Wertung</div>
        <div class="rating left">☆☆☆☆☆<span class="progress" style="width: <?php printf('%2d', $ratingData['sum'] / $ratingData['count']) ?>%"></span></div>
      <?php endif;?>
    </div>
    <div id="product-slider" class="swiper-container">
      <div class="swiper-wrapper">
        <?php if (!empty($_images)) : ?>
          <?php foreach($_images as $child) : ?>
            <div class="swiper-slide">
              <img src="<?php echo $child->getUrl() ?>" alt="<?php echo $_product->getName() ?>" />
            </div>
          <?php endforeach; ?>
        <?php else: ?>
        <?php endif; ?>
      </div>
      <div class="navigate button-prev fa fa-angle-left"></div>
      <div class="navigate button-next fa fa-angle-right"></div>
    </div>
    <div id="product-thumbs" class="swiper-container">
      <div class="swiper-wrapper">
        <?php if (!empty($_images)) : ?>
          <?php foreach($_images as $child) : ?>
            <div class="swiper-slide">
              <img src="<?php echo $child->getUrl() ?>" alt="<?php echo $_product->getName() ?>" />
            </div>
          <?php endforeach; ?>
        <?php else: ?>
        <?php endif; ?>
      </div>
    </div>
    <div class="navigate button-prev fa fa-angle-left"></div>
    <div class="navigate button-next fa fa-angle-right"></div>
  </div>
  <div class="right text product-options">
    <p class="fw-700">
      Kurzbeschreibung
    </p>
    <?php echo $_product->getDescription() ?>
    <div class="divider"></div>
    <form action="<?php echo $block->getSubmitUrl($_product) ?>" method="post" id="add-to-cart">
      <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
      <input type="hidden" name="selected_configurable_option" value="" />
      <input type="hidden" name="related_product" value="" />
      <?php echo $block->getBlockHtml('formkey'); ?>
      <?php echo $block->getChildHtml('form_top'); ?>
      <div class="count fw-500">
        <label>Anzahl</label>
        <input type="number" name="qty" maxlength="3" value="1" min="1" max="999" title="Qty" class="input-number" />
      </div>
      <div class="options">
        <?php if (!empty($productOptions)) : ?>
          <?php foreach ($productOptions as $optionId => $option) : ?>
            <?php foreach ($option['values'] as $optionValue) : ?>
              <div class="option clear">
                <div class="switch left">
                  <input type="radio" name="super_attribute[<?php echo $optionId; ?>]" value="<?php echo $optionValue['value_index']; ?>" id="option-<?php echo $optionValue['value_index']; ?>" />
                  <label for="option-<?php echo $optionValue['value_index']; ?>"></label>
                </div>
                <div class="weight left">
                  <p class="fw-700"><?php echo $optionValue['label']; ?><!-- - (<?php echo $optionValue['label']; ?> / 3,90 €)--> T-Preis</p>
                  <p><?php echo $optionValue['label']; ?><!-- - (<?php echo $optionValue['label']; ?> / 2,53 €) --> <u>C-Preis</u> <img src="<?php echo $this->getViewFileUrl('img/icons/icon-percent-black.png') ?>" valign="middle" alt="Icon percent" /></p>
                </div>
                <div class="price right">
                  <p class="fw-700"><?php printf('%0.2f', $_product->getFinalPrice()) ?>€</p>
                  <p><?php printf('%0.2f', $_product->getFinalPrice()) ?>€</p>
                </div>
              </div>
            <?php endforeach; ?>
          <?php endforeach; ?>
        <?php endif; ?>
      </div>
      <div class="divider"></div>
      <div class="clear total-info">
        <div class="left">
          <p class="gray">Artikelnr.: <?php echo $_product->getSku() ?></p>
          <p class="gray price"><span class="fw-800"><?php printf('%0.2f', $_product->getFinalPrice()) ?>€</span> 4.50€</p>
        </div>
        <div class="right text-right">
          <p class="gray"><img src="<?php echo $this->getViewFileUrl('img/icons/icon-clock.png') ?>" valign="middle" alt="Icon clock" /> Lieferzeit: 3-5 Tage</p>
          <p>inkl. MwSt. zzgl. <u>Versand</u></p>
        </div>
      </div>
      <button type="submit" class="btn-green w100p">DEm Warenkorb hinzufügen</button>
    </form>
  </div>
</div>
