<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <?php echo $block->getBlockHtml('page.main.title'); ?>
    <div class="products <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <?php foreach ($_productCollection as $_product): ?>
            <div class="product">
                <?php
                $productImage = $block->getImage($_product, $image);
                if ($pos != null) {
                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                        . 'top:' . $productImage->getHeight() . 'px;"';
                }
                ?>
                <?php
                  $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                  $images = $product->getMediaGalleryImages();
                ?>
                <div class="category-slider swiper-container">
                  <ul class="swiper-wrapper">
                    <?php if (!empty($images)) : ?>
                      <?php foreach($images as $child) : ?>
                        <li class="swiper-slide">
                          <a href="<?php  echo $_product->getProductUrl() ?>">
                            <img src="<?php echo $child->getUrl() ?>" alt="<?php echo $_product->getName() ?>" />
                          </a>
                        </li>
                      <?php endforeach; ?>
                    <?php else: ?>
                      <li class="swiper-slide">
                        <a href="<?php echo $_product->getProductUrl() ?>">
                          <?php echo $productImage->toHtml(); ?>
                        </a>
                      </li>
                    <?php endif; ?>
                  </ul>
                  <div class="navigate button-prev fa fa-angle-left"></div>
                  <div class="navigate button-next fa fa-angle-right"></div>
                </div>
                <div class="title">
                  <?php /* @escapeNotVerified */ echo $_product->getName() ?>
                </div>
                <div class="rating">☆☆☆☆☆<span class="progress" style="width: <?php echo $_product->getRatingSummary()['rating_summary']; ?>%"></span>
            		</div>
                <div class="price-wrapper">
                  <div class="row">
                    <span class="row-title">T-Preis:</span> <span class="new"><?php printf('%.2f', $_product->getFinalPrice()) ?>€</span> inkl. MwSt.
                  </div>
                  <div class="row">
                    <span class="row-title underline">C-Preis:</span> <span class="new">2.53€</span> inkl. MwSt.
                  </div>
                </div>
                <!-- <div class="product details product-item-details">
                    <div class="product-item-inner">
                        <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                            <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                <?php if ($_product->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                        <?php echo $block->getBlockHtml('formkey')?>
                                        <button type="submit"
                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                class="action tocart primary">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    </form>
                                <?php else: ?>
                                    <?php if ($_product->getIsSalable()): ?>
                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php if ($showDescription):?>
                            <div class="product description product-item-description">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div> -->
            </div>
            <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
        <?php endforeach; ?>
    </div>
    <?php echo  $this->getToolbarBlock()->setTemplate('Magento_Catalog::product/list/pagination.phtml')->toHtml(); ?>
<?php endif; ?>
