<div class="content right">
  <div class="home-slider">
    <div id="home-slider-1" class="swiper-container">
       <ul class="swiper-wrapper">
          <li class="swiper-slide" style="background-image:url('<?php echo $this->getViewFileUrl('img/slider-home/slide-01.jpg'); ?>')">
          </li>
          <li class="swiper-slide" style="background-image:url('<?php echo $this->getViewFileUrl('img/slider-home/slide-01.jpg'); ?>')">
          </li>
          <li class="swiper-slide" style="background-image:url('<?php echo $this->getViewFileUrl('img/slider-home/slide-01.jpg'); ?>')">
          </li>
       </ul>
       <div class="swiper-pagination"></div>
    </div>
  </div>
</div>
