<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<ul class="menu">
  <li class="menu-item icon-menu">
    <span>
      Kategorie Wählen...
    </span>
  </li>
  <li class="menu-item icon-new">
    <a href="#">
      <span>Neue Produkte</span>
    </a>
  </li>
  <li class="menu-item icon-percent">
    <a href="#">
      <span>Angebote</span>
    </a>
  </li>
  <?php /* @escapeNotVerified */ echo $_menu; ?>
</ul>
